# Generated by Django 4.0.5 on 2022-06-19 08:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rest_api.models.chemical_models
import rest_api.models.date_models
import rest_api.models.user_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(default=rest_api.models.user_models.create_id, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='username')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChemicalModel',
            fields=[
                ('id', models.CharField(default=rest_api.models.chemical_models.create_id, editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('used_amount', models.PositiveIntegerField(blank=True, default=0, verbose_name='薬品使用量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='薬品名')),
            ],
        ),
        migrations.CreateModel(
            name='ManageDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_day', models.PositiveIntegerField(default=rest_api.models.date_models.get_day, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='対象の日')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(default=rest_api.models.user_models.create_id, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='YearAndMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_year', models.PositiveIntegerField(default=rest_api.models.date_models.get_year, validators=[django.core.validators.MinValueValidator(2000)], verbose_name='対象の西暦')),
                ('create_month', models.PositiveIntegerField(default=rest_api.models.date_models.get_month, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='対象の月')),
            ],
        ),
        migrations.AddConstraint(
            model_name='yearandmonth',
            constraint=models.UniqueConstraint(fields=('create_year', 'create_month'), name='unique_year_month'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userProfile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managedate',
            name='year_and_month',
            field=models.ManyToManyField(to='rest_api.yearandmonth'),
        ),
        migrations.AddField(
            model_name='chemicalmodel',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.chemicalname', verbose_name='薬品名'),
        ),
        migrations.AddField(
            model_name='chemicalmodel',
            name='used_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_api.managedate', verbose_name='使用した年月'),
        ),
        migrations.AddField(
            model_name='chemicalmodel',
            name='used_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='使用したユーザー'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
