# Generated by Django 4.0.5 on 2022-06-19 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managedate',
            name='year_and_month',
        ),
        migrations.AddField(
            model_name='managedate',
            name='year_and_month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_api.yearandmonth'),
        ),
    ]
